# -*- coding: utf-8 -*-
"""spam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPCW6rehFt-jRPSxaIAnUm7Xbsd83xt1
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score

data = {
    'text': [
        'Congratulations! You have won a lottery of $1000.',
        'Please call me back when you get this message.',
        'You are invited to join a free webinar.',
        'Win a brand new car! Click here to claim your prize.',
        'Can we meet tomorrow at 10 AM?',
        'Exclusive deal just for you! Buy one get one free!',
        'Your appointment is confirmed for tomorrow.',
        'Limited time offer! Get paid to work from home.'
    ],
    'label': ['spam', 'ham', 'ham', 'spam', 'ham', 'spam', 'ham', 'spam']
}

import pandas as pd

# Specify the encoding when reading the CSV file
df = pd.read_csv('/content/spam.csv', encoding='latin-1')  # or 'cp1252' or other encoding if 'latin-1' doesn't work

df = pd.DataFrame(data)

X = df['text']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

y_pred = model.predict(X_test_vectorized)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))